[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder

[platformio]
default_envs = esp32-c6-devkitc-1
