#pragma once

#include "lvgl.h"

// Generated by tools/fonts/generate.sh; do not edit the .c files by hand.
#ifdef __cplusplus
extern "C" {
#endif
LV_FONT_DECLARE(font_bold_40)  // Montserrat Bold: A-Z, 0-9, space
LV_FONT_DECLARE(font_bold_32)  // Montserrat Bold: A-Z, 0-9, space
LV_FONT_DECLARE(font_bold_18)  // Montserrat Bold: 0-9 - ° C %
LV_FONT_DECLARE(icons_60)      // Font Awesome: bin icons
LV_FONT_DECLARE(icons_22)      // Font Awesome: wifi, thermometer, droplet
LV_FONT_DECLARE(icons_30)      // Font Awesome: stale data (clock-rotate-left)
#ifdef __cplusplus
}
#endif

// Font Awesome code points as UTF-8
#define ICON_TRASH_CAN "\xEF\x8B\xAD"   // U+F2ED
#define ICON_RECYCLE "\xEF\x86\xB8"     // U+F1B8
#define ICON_APPLE "\xEF\x97\x91"       // U+F5D1
#define ICON_WIFI "\xEF\x87\xAB"        // U+F1EB
#define ICON_THERMOMETER "\xEF\x8B\x89" // U+F2C9
#define ICON_DROPLET "\xEF\x81\x83"     // U+F043
#define ICON_STALE "\xEF\x87\x9A"       // U+F1DA clock-rotate-left
