#pragma once

#include "lvgl.h"

// Emoji mascot faces, 84px square, pre-dithered 1-bit images. Generated by
// tools/mascot/make_emoji.py.
#ifdef __cplusplus
extern "C" {
#endif
LV_IMAGE_DECLARE(mascot_emoji_happy);
LV_IMAGE_DECLARE(mascot_emoji_wink);
LV_IMAGE_DECLARE(mascot_emoji_excited);  // bin night: star eyes
LV_IMAGE_DECLARE(mascot_emoji_proud);    // collection day: sunglasses
LV_IMAGE_DECLARE(mascot_emoji_worried);  // offline or out of date
LV_IMAGE_DECLARE(mascot_emoji_sleepy);   // low battery
#ifdef __cplusplus
}
#endif
